"""empty message

Revision ID: 62813c99ba8e
Revises: e9084e87b1e3
Create Date: 2019-03-11 22:38:43.066360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62813c99ba8e'
down_revision = 'e9084e87b1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code'),
    sa.UniqueConstraint('name')
    )
    op.add_column('extras', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'extras', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extras', type_='foreignkey')
    op.drop_column('extras', 'country_id')
    op.drop_table('countries')
    # ### end Alembic commands ###
