"""empty message

Revision ID: 97e7f9e4693f
Revises: d46f8964641b
Create Date: 2019-04-19 11:27:55.191794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97e7f9e4693f'
down_revision = 'd46f8964641b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extras', sa.Column('body_image', sa.String(length=255), nullable=True))
    op.add_column('extras', sa.Column('face_image', sa.String(length=255), nullable=True))
    op.drop_column('extras', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extras', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('extras', 'face_image')
    op.drop_column('extras', 'body_image')
    # ### end Alembic commands ###
