"""empty message

Revision ID: d46f8964641b
Revises: 4823204cc03a
Create Date: 2019-03-14 22:37:26.867381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd46f8964641b'
down_revision = '4823204cc03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foot_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trouser_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tshirt_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('extras', sa.Column('foot_size_id', sa.Integer(), nullable=True))
    op.add_column('extras', sa.Column('trouser_size_id', sa.Integer(), nullable=True))
    op.add_column('extras', sa.Column('tshirt_size_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'extras', 'foot_sizes', ['foot_size_id'], ['id'])
    op.create_foreign_key(None, 'extras', 'tshirt_sizes', ['tshirt_size_id'], ['id'])
    op.create_foreign_key(None, 'extras', 'trouser_sizes', ['trouser_size_id'], ['id'])
    op.drop_column('extras', 'foot_size')
    op.drop_column('extras', 'trouser_size')
    op.drop_column('extras', 'tshirt_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extras', sa.Column('tshirt_size', mysql.VARCHAR(length=3), nullable=True))
    op.add_column('extras', sa.Column('trouser_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('extras', sa.Column('foot_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'extras', type_='foreignkey')
    op.drop_constraint(None, 'extras', type_='foreignkey')
    op.drop_constraint(None, 'extras', type_='foreignkey')
    op.drop_column('extras', 'tshirt_size_id')
    op.drop_column('extras', 'trouser_size_id')
    op.drop_column('extras', 'foot_size_id')
    op.drop_table('tshirt_sizes')
    op.drop_table('trouser_sizes')
    op.drop_table('foot_sizes')
    # ### end Alembic commands ###
