"""empty message

Revision ID: e6d9f987a1b3
Revises: 0de89af91406
Create Date: 2019-03-07 23:30:10.824151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6d9f987a1b3'
down_revision = '0de89af91406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extras', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('extras', sa.Column('email', sa.String(length=80), nullable=False))
    op.add_column('extras', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'extras', ['email'])
    op.create_foreign_key(None, 'extras', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=150), nullable=False))
    op.drop_constraint(None, 'extras', type_='foreignkey')
    op.drop_constraint(None, 'extras', type_='unique')
    op.drop_column('extras', 'user_id')
    op.drop_column('extras', 'email')
    op.drop_column('extras', 'created_at')
    # ### end Alembic commands ###
